/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package exp2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int MAIN = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int ADD = 15;
  /** RegularExpression Id. */
  int MUL = 16;
  /** RegularExpression Id. */
  int DIV = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int MOD = 19;
  /** RegularExpression Id. */
  int EQL = 20;
  /** RegularExpression Id. */
  int LB = 21;
  /** RegularExpression Id. */
  int RB = 22;
  /** RegularExpression Id. */
  int RELATIONAL_OPERATOR = 23;
  /** RegularExpression Id. */
  int REQL = 24;
  /** RegularExpression Id. */
  int UEQL = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int LTE = 27;
  /** RegularExpression Id. */
  int RT = 28;
  /** RegularExpression Id. */
  int RTE = 29;
  /** RegularExpression Id. */
  int TYPE = 30;
  /** RegularExpression Id. */
  int VOID = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int FLOAT = 33;
  /** RegularExpression Id. */
  int SEMI = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"%\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "<RELATIONAL_OPERATOR>",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\" >=\"",
    "<TYPE>",
    "\"void\"",
    "\"int\"",
    "\"float\"",
    "\";\"",
    "\",\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
  };

}
