/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package exp2;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTEXPRESSION = 2;
  public int JJTADDITIVEEXPRESSION = 3;
  public int JJTMULTIPLICATIVEEXPRESSION = 4;
  public int JJTUNARYEXPRESSION = 5;
  public int JJTIDENTIFIER = 6;
  public int JJTTYPE = 7;
  public int JJTRELATIONALOPERATOR = 8;
  public int JJTINTEGER = 9;
  public int JJTSTATEMENTBLOCK = 10;
  public int JJTSTATEMENT = 11;
  public int JJTBOOLEXPRESSION = 12;
  public int JJTLOOPSTATEMENT = 13;
  public int JJTWHILESTATEMENT = 14;
  public int JJTSEQSTATEMENT = 15;
  public int JJTDECSTATEMENT = 16;
  public int JJTASSSTATMENT = 17;
  public int JJTCONSTATEMENT = 18;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Type",
    "RelationalOperator",
    "Integer",
    "StatementBlock",
    "Statement",
    "BoolExpression",
    "loopStatement",
    "whileStatement",
    "seqStatement",
    "decStatement",
    "assStatment",
    "conStatement",
  };
}
/* JavaCC - OriginalChecksum=939f751b0d2f70898c3d894dd2b7e44e (do not edit this line) */
