/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammar.java */
package parser;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Iterator;

import util.*;

public class MyNewGrammar/*@bgen(jjtree)*/implements MyNewGrammarTreeConstants, MyNewGrammarConstants {/*@bgen(jjtree)*/
  protected JJTMyNewGrammarState jjtree = new JJTMyNewGrammarState();static public QTTable qtTable = new QTTable();

  public static ArrayList < String > errorList = new ArrayList < String > ();

  public static ArrayList < Token > tokenList = new ArrayList < Token > ();

  public void printQTList()
  {
    qtTable.printQTTable();
  }
  public static void main(String args [])
  {
    try
    {
      InputStream in = new FileInputStream("Input.txt"); //与项目文件夹下的Input.txt文件建立输入流
      OutputStream out = new FileOutputStream("Output.txt"); //与项目文件夹下的Output.txt文件建立输出流
      MyNewGrammarTokenManager manager = new MyNewGrammarTokenManager(new SimpleCharStream(in));//通过JavaCC自带的两个类进行数据的输入
      Token t;
      t = manager.getNextToken();//通过getNextToken获取数据
      while(t.kind != 0) {//当读到数据的结尾，即EOF时，其内部的标识符为0，所以以此为结束标志
                out.write(("(" + t.kind + ", " + t.image + ")\u005cn").getBytes());//输出内部标识符与自身
        t = manager.getNextToken();
      }
      in.close();
      in = new FileInputStream("Input.txt");//关闭并重新建立输出流，以重置读取进度
      MyNewGrammar parser = new MyNewGrammar(in);
      SimpleNode n = parser.Start();
      n.dump("", out); //使用重载后的分析程序
      out.write("\u005cn".getBytes());
      qtTable.printQTTable(out);
      System.out.println("Thank you.");
      in.close();
      out.close();
    }
    catch (Exception e)
    {
      System.out.println("Oops.");
      System.out.println(e.getMessage());
    }
  }

  public static void dealData(String filename)
  {
        VariableNameGenerator.sequenceId = 0;//进行数据的初始化
        errorList.clear();
        tokenList.clear();
        qtTable.clear();
    try
    {
      InputStream in = new FileInputStream(filename); //指定文件建立输入流
      OutputStream out = new FileOutputStream("Output.txt"); //与项目文件夹下的Output.txt文件建立输出流
      MyNewGrammarTokenManager manager = new MyNewGrammarTokenManager(new SimpleCharStream(in));//通过JavaCC自带的两个类进行数据的输入
      Token t;
      t = manager.getNextToken();//通过getNextToken获取数据
      while(t.kind != 0) {//当读到数据的结尾，即EOF时，其内部的标识符为0，所以以此为结束标志
                out.write(("(" + t.kind + ", " + t.image + ")\u005cn").getBytes());//输出内部标识符与自身
        t = manager.getNextToken();
      }
      in.close();
      in = new FileInputStream("Input.txt");//关闭并重新建立输出流，以重置读取进度
      MyNewGrammar parser = new MyNewGrammar(in);
      SimpleNode n = parser.Start();
      n.dump("", out); //使用重载后的分析程序
      out.write("\u005cn".getBytes());
      qtTable.printQTTable(out);
      out.write("\u005cn".getBytes());
          Iterator<Token> itr =  tokenList.iterator();
          while(itr.hasNext())
          {
            Token tmp = (Token) itr.next();
                out.write((tmp.showInfo() + "\u005cn").getBytes());//向文件中写入符号表
          }
      in.close();
      out.close();
    }
    catch (Exception e)
    {
      errorList.add(e.getMessage());
    }
  }
  boolean checkExsit(String image)
  {
    if(tokenList.isEmpty() == true) return false;
    Iterator<Token> itr = tokenList.iterator();
        while(itr.hasNext())
        {
          Token tmp = (Token) itr.next();
          if(tmp.image.equals(image))
          {
            return true;
          }
        }
        return false;
  }

//程序的入口
  final public SimpleNode Start() throws ParseException {
 /*@bgen(jjtree) Start */
  SimpleNode jjtn000 = new SimpleNode(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Program();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//程序
  final public void Program() throws ParseException {
 /*@bgen(jjtree) Program */
  SimpleNode jjtn000 = new SimpleNode(JJTPROGRAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Type();
      jj_consume_token(MAIN);
      jj_consume_token(LP);
      jj_consume_token(RP);
      jj_consume_token(LB);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IF:
        case WHILE:
        case DO:
        case FOR:
        case SWITCH:
        case SELFADD:
        case SELFMINUS:
        case TYPE:
        case LB:
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        SentenceBlock();
      }
      jj_consume_token(RB);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//表达式
  final public String Expression() throws ParseException {
 /*@bgen(jjtree) Expression */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String s = null;
    try {
      s = AdditiveExpression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return s;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String AdditiveExpression() throws ParseException {
 /*@bgen(jjtree) AdditiveExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTADDITIVEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String a = null;
  String b = null;
  String result = null;
  Token t = null;
    try {
      a = MultiplicativeExpression();
    result = a;
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ADD:
        case MINUS:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_2;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ADD:
          t = jj_consume_token(ADD);
          break;
        case MINUS:
          t = jj_consume_token(MINUS);
          break;
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = MultiplicativeExpression();
      result = VariableNameGenerator.genVariableName();
      QTInfo qtInfo = new QTInfo(t.image, a, b, result);
      qtTable.addQTInfo(qtInfo);
      a = result;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return result;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String MultiplicativeExpression() throws ParseException {
 /*@bgen(jjtree) MultiplicativeExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTMULTIPLICATIVEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String a = null;
  String b = null;
  String result = null;
  Token t = null;
    try {
      a = UnaryExpression();
    result = a;
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MUL:
        case DIV:
        case MOD:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MUL:
          t = jj_consume_token(MUL);
          break;
        case DIV:
          t = jj_consume_token(DIV);
          break;
        case MOD:
          t = jj_consume_token(MOD);
          break;
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = UnaryExpression();
      result = VariableNameGenerator.genVariableName();
      QTInfo qtInfo = new QTInfo(t.image, a, b, result);
      qtTable.addQTInfo(qtInfo);
      a = result;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return result;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String UnaryExpression() throws ParseException {
 /*@bgen(jjtree) UnaryExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTUNARYEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String s = null;
  Token t = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LP:
        jj_consume_token(LP);
        s = Expression();
        jj_consume_token(RP);
        break;
      case IDENTIFIER:
        t = Identifier();
            s = t.image;
        if(this.checkExsit(t.image) == false)
        {
          errorList.add(t.endLine + "\u884c" + t.endColumn + "\u5217\uff1a" + "\u53d8\u91cf"
          + t.image + "\u672a\u5b9a\u4e49");
        }
        break;
      case INTEGER_LITERAL:
        s = Integer();
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return s;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//类型
  final public String Type() throws ParseException {
 /*@bgen(jjtree) Type */
  SimpleNode jjtn000 = new SimpleNode(JJTTYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String s = null;
    try {
      s = jj_consume_token(TYPE).image;
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return s;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//标识符
  final public Token Identifier() throws ParseException {
 /*@bgen(jjtree) Identifier */
  SimpleNode jjtn000 = new SimpleNode(JJTIDENTIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t = null;
    try {
      t = jj_consume_token(IDENTIFIER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return t;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//关系表达式
  final public void RelationalOperator() throws ParseException {
 /*@bgen(jjtree) RelationalOperator */
  SimpleNode jjtn000 = new SimpleNode(JJTRELATIONALOPERATOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RELATIONAL_OPERATOR);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public String Integer() throws ParseException {
 /*@bgen(jjtree) Integer */
  SimpleNode jjtn000 = new SimpleNode(JJTINTEGER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t = null;
    try {
      t = jj_consume_token(INTEGER_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return t.image;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void SentenceBlock() throws ParseException {
 /*@bgen(jjtree) SentenceBlock */
  SimpleNode jjtn000 = new SimpleNode(JJTSENTENCEBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case DO:
      case FOR:
      case SWITCH:
      case SELFADD:
      case SELFMINUS:
      case TYPE:
      case IDENTIFIER:
        Sentence();
        break;
      case LB:
        jj_consume_token(LB);
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IF:
          case WHILE:
          case DO:
          case FOR:
          case SWITCH:
          case SELFADD:
          case SELFMINUS:
          case TYPE:
          case LB:
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[6] = jj_gen;
            break label_4;
          }
          SentenceBlock();
        }
        jj_consume_token(RB);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//语句
  final public void Sentence() throws ParseException {
 /*@bgen(jjtree) Sentence */
  SimpleNode jjtn000 = new SimpleNode(JJTSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SELFADD:
      case SELFMINUS:
      case TYPE:
      case IDENTIFIER:
        seqSentence();
        break;
      case IF:
        conSentence();
        break;
      case WHILE:
        whileSentence();
        break;
      case DO:
        doWhileSentence();
        break;
      case FOR:
        forSentence();
        break;
      case SWITCH:
        switchSentence();
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//逻辑表达式，按运算顺序，从逻辑或开始识别
  final public ConditionValue logExpression() throws ParseException {
 /*@bgen(jjtree) logExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTLOGEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
    try {
      cValue = orExpression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return cValue;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//逻辑或
  final public ConditionValue orExpression() throws ParseException {
 /*@bgen(jjtree) orExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTOREXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue1 = new ConditionValue();
  ConditionValue cValue2 = new ConditionValue();
    try {
      cValue1 = andExpression();
    cValue2 = cValue1;
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OR:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_5;
        }
        jj_consume_token(OR);
      cValue1.backpatchFalseChain(QTInfo.innerIdSeqen + 1);
        cValue2 = andExpression();
          cValue2.trueChain.addAll(cValue1.trueChain);
      cValue1 = cValue2;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return cValue2;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//逻辑与
  final public ConditionValue andExpression() throws ParseException {
 /*@bgen(jjtree) andExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTANDEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue1 = new ConditionValue();
  ConditionValue cValue2 = new ConditionValue();
    try {
      cValue1 = notExpression();
    cValue2 = cValue1;
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND:
          ;
          break;
        default:
          jj_la1[10] = jj_gen;
          break label_6;
        }
        jj_consume_token(AND);
      cValue1.backpatchTrueChain(QTInfo.innerIdSeqen + 1);
        cValue2 = notExpression();
          cValue2.falseChain.addAll(cValue1.falseChain);
      cValue1 = cValue2;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return cValue2;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//逻辑非
  final public ConditionValue notExpression() throws ParseException {
 /*@bgen(jjtree) notExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTNOTEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue1 = new ConditionValue();
  ConditionValue cValue2 = new ConditionValue();
  boolean flag = true;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
        jj_consume_token(NOT);
    flag = false;
        break;
      default:
        jj_la1[11] = jj_gen;
        ;
      }
      cValue2 = relationalExpression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    if(flag)
    {
      cValue1.trueChain = cValue2.trueChain;
      cValue1.falseChain = cValue2.falseChain;
    }
    else
    {
      cValue1.trueChain = cValue2.falseChain;
      cValue1.falseChain = cValue2.trueChain;
    }
    {if (true) return cValue1;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

//关系表达式
  final public ConditionValue relationalExpression() throws ParseException {
 /*@bgen(jjtree) relationalExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTRELATIONALEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t = null;
  String e1 = null;
  String e2 = null;
  ConditionValue cValue = new ConditionValue();
    try {
      e1 = Expression();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RELATIONAL_OPERATOR:
          ;
          break;
        default:
          jj_la1[12] = jj_gen;
          break label_7;
        }
        t = jj_consume_token(RELATIONAL_OPERATOR);
        e2 = Expression();
      }
    if (t == null)
    {
      QTInfo qtInfo = new QTInfo("jnz", e1, "_", "T");
      qtTable.addQTInfo(qtInfo);
      cValue.mergeTrue(qtInfo);
    }
    else
    {
      QTInfo qtInfo = new QTInfo("j" + t.image, e1, e2, "T");
      qtTable.addQTInfo(qtInfo);
      cValue.mergeTrue(qtInfo);
    }
    QTInfo qtInfo = new QTInfo("j", "_", "_", "F");
    qtTable.addQTInfo(qtInfo);
    cValue.mergeFalse(qtInfo);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return cValue;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void conSentence() throws ParseException {
 /*@bgen(jjtree) conSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTCONSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
  int index = 0;
    try {
      jj_consume_token(IF);
      jj_consume_token(LP);
      cValue = logExpression();
      jj_consume_token(RP);
    cValue.backpatchTrueChain(QTInfo.innerIdSeqen + 1);
      SentenceBlock();
    cValue.backpatchFalseChain(QTInfo.innerIdSeqen + 1);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
      QTInfo qtInfo = new QTInfo("j", "_", "_", "");
      qtTable.addQTInfo(qtInfo);
      index = QTInfo.innerIdSeqen;
      cValue.backpatchFalseChain(QTInfo.innerIdSeqen + 1);
        SentenceBlock();
          qtInfo = qtTable.get(index - 1);
      qtInfo.setResult(QTInfo.innerIdSeqen + 1);
        break;
      default:
        jj_la1[13] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void LogicalOperators() throws ParseException {
 /*@bgen(jjtree) LogicalOperators */
  SimpleNode jjtn000 = new SimpleNode(JJTLOGICALOPERATORS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        jj_consume_token(AND);
        break;
      case OR:
        jj_consume_token(OR);
        break;
      case NOT:
        jj_consume_token(NOT);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//while循环语句
  final public void whileSentence() throws ParseException {
 /*@bgen(jjtree) whileSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILESENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
  int index = 0;
    try {
      jj_consume_token(WHILE);
      jj_consume_token(LP);
      index = QTInfo.innerIdSeqen + 1;
      cValue = logExpression();
      jj_consume_token(RP);
    cValue.backpatchTrueChain(QTInfo.innerIdSeqen + 1);
      SentenceBlock();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    QTInfo qtInfo = new QTInfo("j", "_", "_", index);
    qtTable.addQTInfo(qtInfo);
    cValue.backpatchFalseChain(QTInfo.innerIdSeqen + 1);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//dowhile循环语句
  final public void doWhileSentence() throws ParseException {
 /*@bgen(jjtree) doWhileSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTDOWHILESENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
  int index = 0;
    try {
      jj_consume_token(DO);
    index = QTInfo.innerIdSeqen + 1;
      SentenceBlock();
      jj_consume_token(WHILE);
      jj_consume_token(LP);
      cValue = logExpression();
      jj_consume_token(RP);
    cValue.backpatchTrueChain(index);
    cValue.backpatchFalseChain(QTInfo.innerIdSeqen + 1);
      jj_consume_token(SEMI);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//自增自减识别，主要用于for循环
  final public void selfDeal() throws ParseException {
 /*@bgen(jjtree) selfDeal */
  SimpleNode jjtn000 = new SimpleNode(JJTSELFDEAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token op = null;
  Token e = null;
  String t = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        e = Identifier();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SELFADD:
          op = jj_consume_token(SELFADD);
          break;
        case SELFMINUS:
          op = jj_consume_token(SELFMINUS);
          break;
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case SELFADD:
      case SELFMINUS:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SELFADD:
          op = jj_consume_token(SELFADD);
          break;
        case SELFMINUS:
          op = jj_consume_token(SELFMINUS);
          break;
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        e = Identifier();
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        System.out.println("do");
    if(this.checkExsit(e.image) == false)
    {
      errorList.add(e.endLine + "\u884c" + e.endColumn + "\u5217\uff1a" + "\u53d8\u91cf"
      + e.image + "\u672a\u5b9a\u4e49");
    }
        t = VariableNameGenerator.genVariableName();
    QTInfo qtInfo = new QTInfo(op.image.substring(0, 1), "1", e.image, t);
    qtTable.addQTInfo(qtInfo);
    qtInfo = new QTInfo("=", t, "_", e.image);
    qtTable.addQTInfo(qtInfo);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//for循环语句
  final public void forSentence() throws ParseException {
 /*@bgen(jjtree) forSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTFORSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
  int result1 = 0;
  int result2 = 0;
    try {
      jj_consume_token(FOR);
      jj_consume_token(LP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TYPE:
      case IDENTIFIER:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case TYPE:
          decSentence();
          break;
        case IDENTIFIER:
          assSentence();
          break;
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      jj_consume_token(SEMI);
    result1 = QTInfo.innerIdSeqen + 1;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
      case NOT:
      case LP:
      case IDENTIFIER:
        cValue = logExpression();
     result2 = QTInfo.innerIdSeqen + 1;
        break;
      default:
        jj_la1[20] = jj_gen;
        ;
      }
      jj_consume_token(SEMI);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SELFADD:
      case SELFMINUS:
      case IDENTIFIER:
        if (jj_2_1(2)) {
          selfDeal();
      QTInfo qtInfo = new QTInfo("j", "_", "_", result1);
      qtTable.addQTInfo(qtInfo);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            assSentence();
            break;
          default:
            jj_la1[21] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      jj_consume_token(RP);
    cValue.backpatchTrueChain(QTInfo.innerIdSeqen + 1);
      SentenceBlock();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    QTInfo qtInfo = new QTInfo("j", "_", "_", result2);
    qtTable.addQTInfo(qtInfo);
    cValue.backpatchFalseChain(QTInfo.innerIdSeqen + 1);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//switch选择语句
  final public void switchSentence() throws ParseException {
 /*@bgen(jjtree) switchSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTSWITCHSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String e1 = null;
  String e2 = null;
  int index = 0;
  int last = 0;
  boolean flag = false;
  ConditionValue cValue = new ConditionValue();
    try {
      jj_consume_token(SWITCH);
      jj_consume_token(LP);
      e1 = Expression();
      jj_consume_token(RP);
      jj_consume_token(LB);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CASE:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_8;
        }
        jj_consume_token(CASE);
        e2 = Expression();
        jj_consume_token(59);
        QTInfo qtInfo = new QTInfo("jne", e1, e2, "");
        qtTable.addQTInfo(qtInfo);
        index = QTInfo.innerIdSeqen;
        label_9:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IF:
          case WHILE:
          case DO:
          case FOR:
          case SWITCH:
          case SELFADD:
          case SELFMINUS:
          case TYPE:
          case LB:
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[24] = jj_gen;
            break label_9;
          }
          SentenceBlock();
        }
                if(flag == false)
                {
                  cValue.backpatchFalseChain(index + 1);
                  cValue.clearFalse();
                }
                flag = false;

        qtInfo = new QTInfo("j", "_", "_", "");
        qtTable.addQTInfo(qtInfo);
        qtInfo = qtTable.get(index - 1);
        qtInfo.setResult(QTInfo.innerIdSeqen + 1);

        index = QTInfo.innerIdSeqen;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 60:
          jj_consume_token(60);
          flag = true;
          break;
        default:
          jj_la1[25] = jj_gen;
          ;
        }
        qtInfo = qtTable.get(index - 1);
        if(flag == true)
        {
          cValue.mergeTrue(qtInfo);
        }
        else
        {
          cValue.mergeFalse(qtInfo);
        }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SDEFAULT:
        jj_consume_token(SDEFAULT);
        jj_consume_token(59);
        SentenceBlock();
        break;
      default:
        jj_la1[26] = jj_gen;
        ;
      }
      cValue.backpatchTrueChain(QTInfo.innerIdSeqen + 1);
      jj_consume_token(RB);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//顺序语句
  final public void seqSentence() throws ParseException {
 /*@bgen(jjtree) seqSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTSEQSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TYPE:
        decSentence();
        break;
      default:
        jj_la1[27] = jj_gen;
        if (jj_2_2(2)) {
          assSentence();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case SELFADD:
          case SELFMINUS:
          case IDENTIFIER:
            selfDeal();
            break;
          default:
            jj_la1[28] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
      jj_consume_token(SEMI);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//声明语句
  final public void decSentence() throws ParseException {
 /*@bgen(jjtree) decSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTDECSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String type = null;
  Token t = null;
  String e;
    try {
      type = Type();
      t = Identifier();
    if(this.checkExsit(t.image))
    {
      errorList.add(t.endLine + "\u884c" + t.endColumn +"\u5217\uff1a" + "\u53d8\u91cf"
      + t.image + "\u91cd\u590d\u5b9a\u4e49");
    }
    else
    {
          t.type = type;
      tokenList.add(t);
    }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQL:
        jj_consume_token(EQL);
        e = Expression();
      QTInfo qtInfo = new QTInfo("=", e, "_", t.image);
      qtTable.addQTInfo(qtInfo);
        break;
      default:
        jj_la1[29] = jj_gen;
        ;
      }
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[30] = jj_gen;
          break label_10;
        }
        jj_consume_token(COMMA);
        t = Identifier();
      if(this.checkExsit(t.image))
      {
        errorList.add(t.endLine + "\u884c" + t.endColumn +"\u5217\uff1a" + "\u53d8\u91cf"
        + t.image + "\u91cd\u590d\u5b9a\u4e49");
      }
      else
      {
            t.type = type;
        tokenList.add(t);
      }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case EQL:
          jj_consume_token(EQL);
          e = Expression();
        QTInfo qtInfo = new QTInfo("=", e, "_", t.image);
        qtTable.addQTInfo(qtInfo);
          break;
        default:
          jj_la1[31] = jj_gen;
          ;
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//赋值语句
  final public void assSentence() throws ParseException {
 /*@bgen(jjtree) assSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTASSSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String arg1 = null;
  Token result = null;
    try {
      result = Identifier();
      jj_consume_token(EQL);
      arg1 = Expression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    if(this.checkExsit(result.image) == false)
    {
      errorList.add(result.endLine + "\u884c" + result.endColumn + "\u5217\uff1a" + "\u53d8\u91cf"
      + result.image + "\u672a\u5b9a\u4e49");
    }
    QTInfo qtInfo = new QTInfo("=", arg1, "_", result.image);
    qtTable.addQTInfo(qtInfo);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) return true;
    }
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_3R_15()) return true;
    if (jj_scan_token(EQL)) return true;
    return false;
  }

  private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_13()) {
    jj_scanpos = xsp;
    if (jj_3R_14()) return true;
    }
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_3R_15()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) return true;
    }
    return false;
  }

  /** Generated Token Manager. */
  public MyNewGrammarTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[32];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x3003d000,0x2400000,0x2400000,0x5800000,0x5800000,0x80,0x3003d000,0x3003d000,0x3003d000,0x80000000,0x40000000,0x0,0x0,0x2000,0xc0000000,0x30000000,0x30000000,0x30000000,0x0,0x0,0x80,0x0,0x30000000,0x80000,0x3003d000,0x0,0x40000,0x0,0x30000000,0x8000000,0x0,0x8000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x1040100,0x0,0x0,0x0,0x0,0x1400000,0x1040100,0x1040100,0x1000100,0x0,0x0,0x1,0x2,0x0,0x1,0x0,0x0,0x1000000,0x1000100,0x1000100,0x1400001,0x1000000,0x1000000,0x0,0x1040100,0x10000000,0x0,0x100,0x1000000,0x0,0x20000,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MyNewGrammar(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MyNewGrammar(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MyNewGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MyNewGrammar(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MyNewGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MyNewGrammar(MyNewGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MyNewGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[61];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 32; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 61; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
