/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package parser;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTEXPRESSION = 2;
  public int JJTADDITIVEEXPRESSION = 3;
  public int JJTMULTIPLICATIVEEXPRESSION = 4;
  public int JJTUNARYEXPRESSION = 5;
  public int JJTTYPE = 6;
  public int JJTIDENTIFIER = 7;
  public int JJTRELATIONALOPERATOR = 8;
  public int JJTINTEGER = 9;
  public int JJTSENTENCEBLOCK = 10;
  public int JJTSENTENCE = 11;
  public int JJTLOGEXPRESSION = 12;
  public int JJTOREXPRESSION = 13;
  public int JJTANDEXPRESSION = 14;
  public int JJTNOTEXPRESSION = 15;
  public int JJTRELATIONALEXPRESSION = 16;
  public int JJTCONSENTENCE = 17;
  public int JJTLOGICALOPERATORS = 18;
  public int JJTWHILESENTENCE = 19;
  public int JJTDOWHILESENTENCE = 20;
  public int JJTSELFDEAL = 21;
  public int JJTFORSENTENCE = 22;
  public int JJTSWITCHSENTENCE = 23;
  public int JJTSEQSENTENCE = 24;
  public int JJTDECSENTENCE = 25;
  public int JJTASSSENTENCE = 26;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Type",
    "Identifier",
    "RelationalOperator",
    "Integer",
    "SentenceBlock",
    "Sentence",
    "logExpression",
    "orExpression",
    "andExpression",
    "notExpression",
    "relationalExpression",
    "conSentence",
    "LogicalOperators",
    "whileSentence",
    "doWhileSentence",
    "selfDeal",
    "forSentence",
    "switchSentence",
    "seqSentence",
    "decSentence",
    "assSentence",
  };
}
/* JavaCC - OriginalChecksum=7ff093d86e30dc57130055bf74e7c1e4 (do not edit this line) */
