/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int MAIN = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int FOR = 16;
  /** RegularExpression Id. */
  int SWITCH = 17;
  /** RegularExpression Id. */
  int SDEFAULT = 18;
  /** RegularExpression Id. */
  int CASE = 19;
  /** RegularExpression Id. */
  int TURE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int ADD = 22;
  /** RegularExpression Id. */
  int MUL = 23;
  /** RegularExpression Id. */
  int DIV = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MOD = 26;
  /** RegularExpression Id. */
  int EQL = 27;
  /** RegularExpression Id. */
  int SELFADD = 28;
  /** RegularExpression Id. */
  int SELFMINUS = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int RELATIONAL_OPERATOR = 33;
  /** RegularExpression Id. */
  int REQL = 34;
  /** RegularExpression Id. */
  int UEQL = 35;
  /** RegularExpression Id. */
  int LT = 36;
  /** RegularExpression Id. */
  int LTE = 37;
  /** RegularExpression Id. */
  int RT = 38;
  /** RegularExpression Id. */
  int RTE = 39;
  /** RegularExpression Id. */
  int TYPE = 40;
  /** RegularExpression Id. */
  int VOID = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int LONGLONG = 43;
  /** RegularExpression Id. */
  int FLOAT = 44;
  /** RegularExpression Id. */
  int DOUBLE = 45;
  /** RegularExpression Id. */
  int CHAR = 46;
  /** RegularExpression Id. */
  int STRING = 47;
  /** RegularExpression Id. */
  int SEMI = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int LB = 50;
  /** RegularExpression Id. */
  int RB = 51;
  /** RegularExpression Id. */
  int LBK = 52;
  /** RegularExpression Id. */
  int RBK = 53;
  /** RegularExpression Id. */
  int LP = 54;
  /** RegularExpression Id. */
  int RP = 55;
  /** RegularExpression Id. */
  int IDENTIFIER = 56;
  /** RegularExpression Id. */
  int LETTER = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"switch\"",
    "\"default\"",
    "\"case\"",
    "\"ture\"",
    "\"false\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"%\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<RELATIONAL_OPERATOR>",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\" >=\"",
    "<TYPE>",
    "\"void\"",
    "\"int\"",
    "\"long long\"",
    "\"float\"",
    "\"double\"",
    "\"char\"",
    "\"string\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\":\"",
    "\"break;\"",
  };

}
