/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package exp3;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTEXPRESSION = 2;
  public int JJTADDITIVEEXPRESSION = 3;
  public int JJTMULTIPLICATIVEEXPRESSION = 4;
  public int JJTUNARYEXPRESSION = 5;
  public int JJTIDENTIFIER = 6;
  public int JJTTYPE = 7;
  public int JJTRELATIONALOPERATOR = 8;
  public int JJTINTEGER = 9;
  public int JJTSENTENCEBLOCK = 10;
  public int JJTSENTENCE = 11;
  public int JJTLOOPSENTENCE = 12;
  public int JJTWHILESENTENCE = 13;
  public int JJTSEQSENTENCE = 14;
  public int JJTDECSENTENCE = 15;
  public int JJTASSSENTENCE = 16;
  public int JJTCONSENTENCE = 17;
  public int JJTLOGICALOPERATORS = 18;
  public int JJTLOGIC = 19;
  public int JJTCONDITION = 20;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Type",
    "RelationalOperator",
    "Integer",
    "SentenceBlock",
    "Sentence",
    "loopSentence",
    "whileSentence",
    "seqSentence",
    "decSentence",
    "assSentence",
    "conSentence",
    "LogicalOperators",
    "Logic",
    "Condition",
  };
}
/* JavaCC - OriginalChecksum=bd4d2f54c94023ca6617d7b8bb101009 (do not edit this line) */
